### ISSUE TITLE
Add a link to Crazyflie GUI client documentation on left sidebar of wiki.

### ISSUE THREAD

**Issue by cstanke** [bitcraze/doc-src#1]
I'm not sure this is the right place to log an issue against the wiki but since this tracks some wiki items, I thought it was appropriate.

It would be good to add a link to the [Crazyflie GUI client page](https://wiki.bitcraze.io/doc:crazyflie:client:pycfclient:index) on the left side-bar of the wiki. I added the link to the "Documentation" section of the front-page but before this the only place it could be found was on the "Crazyflie Nano" project page. Even in the Documentation section it can be obscured "below the fold" on shorter monitors or laptop screens. It would be good to have the link more exposed on the wiki.

**Comment by krichardsson** [comment]
Good point. I added it to the doc section of the left menu.

Thanks!
